# -*- coding: utf-8 -*-
"""dkareliya.kareliya (Jun 10, 2026, 11:51:44 AM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/automl-vs-custom-training/locations/asia-south1/repositories/09aa8ce4-99f1-45cb-bae2-94c21f76a995
"""

import os

os.environ['KAGGLE_API_TOKEN'] = "KGAT_5447ee235bcf8d268b95c80465443c8f"

# Download the dataset
# !kaggle datasets download -d mateuszbuda/lgg-mri-segmentation

# Create directory structure
# !mkdir -p /kaggle/input/lgg-mri-segmentation
# !mkdir -p /kaggle/working/

# Unzip the data into the input folder
# !unzip -q lgg-mri-segmentation.zip -d /kaggle/input/lgg-mri-segmentation

import glob
import random
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms.functional as TF
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import matplotlib.pyplot as plt
from tqdm import tqdm

print(torch.__version__)

class LGGDataset(Dataset):
    def __init__(self, mask_paths, img_size=(256, 256), train=True):
        self.mask_paths = mask_paths
        self.img_size = img_size
        self.train = train

    def __len__(self):
        return len(self.mask_paths)

    def __getitem__(self, idx):
        mask_path = self.mask_paths[idx]
        image_path = mask_path.replace('_mask.tif', '.tif')

        image = Image.open(image_path).convert("RGB")
        mask = Image.open(mask_path).convert("L")

        image = TF.resize(image, self.img_size)
        mask = TF.resize(mask, self.img_size)

        if self.train:
            if random.random() > 0.5:
                image = TF.hflip(image)
                mask = TF.hflip(mask)
            if random.random() > 0.5:
                image = TF.vflip(image)
                mask = TF.vflip(mask)

        image = TF.to_tensor(image)
        mask = TF.to_tensor(mask)
        mask = (mask > 0.5).float()

        return image, mask

class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.double_conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels), nn.ReLU(inplace=True)
        )
    def forward(self, x): return self.double_conv(x)

class UNet(nn.Module):
    def __init__(self, in_channels=3, out_channels=1):
        super().__init__()
        self.down1 = DoubleConv(in_channels, 64)
        self.pool1 = nn.MaxPool2d(2)
        self.down2 = DoubleConv(64, 128)
        self.pool2 = nn.MaxPool2d(2)
        self.down3 = DoubleConv(128, 256)
        self.pool3 = nn.MaxPool2d(2)
        self.down4 = DoubleConv(256, 512)
        self.pool4 = nn.MaxPool2d(2)
        self.bottleneck = DoubleConv(512, 1024)

        self.up1 = nn.ConvTranspose2d(1024, 512, 2, stride=2)
        self.conv_up1 = DoubleConv(1024, 512)
        self.up2 = nn.ConvTranspose2d(512, 256, 2, stride=2)
        self.conv_up2 = DoubleConv(512, 256)
        self.up3 = nn.ConvTranspose2d(256, 128, 2, stride=2)
        self.conv_up3 = DoubleConv(256, 128)
        self.up4 = nn.ConvTranspose2d(128, 64, 2, stride=2)
        self.conv_up4 = DoubleConv(128, 64)
        self.out = nn.Conv2d(64, out_channels, 1)

    def forward(self, x):
        d1 = self.down1(x)
        d2 = self.down2(self.pool1(d1))
        d3 = self.down3(self.pool2(d2))
        d4 = self.down4(self.pool3(d3))
        bn = self.bottleneck(self.pool4(d4))

        u1 = self.conv_up1(torch.cat([self.up1(bn), d4], dim=1))
        u2 = self.conv_up2(torch.cat([self.up2(u1), d3], dim=1))
        u3 = self.conv_up3(torch.cat([self.up3(u2), d2], dim=1))
        u4 = self.conv_up4(torch.cat([self.up4(u3), d1], dim=1))
        return self.out(u4)

class BCEDiceLoss(nn.Module):
    def __init__(self, smooth=1e-5):
        super(BCEDiceLoss, self).__init__()
        self.smooth = smooth
        self.bce = nn.BCEWithLogitsLoss()

    def forward(self, logits, targets):
        bce_loss = self.bce(logits, targets)
        preds = torch.sigmoid(logits).view(-1)
        targets_flat = targets.view(-1)

        intersection = (preds * targets_flat).sum()
        dice_score = (2. * intersection + self.smooth) / (preds.sum() + targets_flat.sum() + self.smooth)
        return bce_loss + (1.0 - dice_score)

def compute_metrics(logits, targets, smooth=1e-5):
    preds = (torch.sigmoid(logits) > 0.5).float().view(-1)
    targets_flat = targets.view(-1)

    intersection = (preds * targets_flat).sum()
    union = preds.sum() + targets_flat.sum() - intersection

    iou = (intersection + smooth) / (union + smooth)
    dice = (2. * intersection + smooth) / (preds.sum() + targets_flat.sum() + smooth)
    return iou.item(), dice.item()

def visualize_predictions(model, val_loader, device, num_samples=3):

    model.eval()
    images, masks = next(iter(val_loader))
    images, masks = images.to(device), masks.to(device)

    with torch.no_grad():
        logits = model(images)
        preds = (torch.sigmoid(logits) > 0.5).float()


    images = images.cpu().permute(0, 2, 3, 1)
    masks = masks.cpu().squeeze(1)
    preds = preds.cpu().squeeze(1)

    fig, axes = plt.subplots(num_samples, 3, figsize=(10, 3 * num_samples))
    for i in range(num_samples):
        axes[i, 0].imshow(images[i])
        axes[i, 0].set_title("MRI Scan")
        axes[i, 0].axis("off")

        axes[i, 1].imshow(masks[i], cmap='gray')
        axes[i, 1].set_title("Ground Truth Mask")
        axes[i, 1].axis("off")

        axes[i, 2].imshow(preds[i], cmap='gray')
        axes[i, 2].set_title("Model Prediction")
        axes[i, 2].axis("off")


    plt.tight_layout()
    plt.show()

def training():

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    print("Searching for dataset...")
    all_mask_paths = glob.glob('/kaggle/input/**/*_mask.tif', recursive=True)

    if len(all_mask_paths) == 0:

        print("\nAvailable directories in /kaggle/input/:")

        for root, dirs, files in os.walk('/kaggle/input/'):
            print(root)
        raise ValueError("Dataset not found!")

    print(f"Success! Found {len(all_mask_paths)} mask files.")

    random.shuffle(all_mask_paths)

    # Hyperparameters
    batch_size = 16
    lr = 1e-4
    epochs = 15

    # Train/Val Split (80/20)
    split_idx = int(0.8 * len(all_mask_paths))
    train_loader = DataLoader(LGGDataset(all_mask_paths[:split_idx], train=True), batch_size=batch_size, shuffle=True, num_workers=2)
    val_loader = DataLoader(LGGDataset(all_mask_paths[split_idx:], train=False), batch_size=batch_size, shuffle=False, num_workers=2)

    model = UNet(in_channels=3, out_channels=1).to(device)
    criterion = BCEDiceLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    print("Starting Training...")
    for epoch in range(epochs):
        model.train()
        train_loss, train_iou, train_dice = 0.0, 0.0, 0.0


        loop = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} [Train]", leave=False)
        for images, masks in loop:
            images, masks = images.to(device), masks.to(device)
            optimizer.zero_grad()
            logits = model(images)
            loss = criterion(logits, masks)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            iou, dice = compute_metrics(logits, masks)
            train_iou += iou
            train_dice += dice
            loop.set_postfix(loss=loss.item())


        model.eval()
        val_loss, val_iou, val_dice = 0.0, 0.0, 0.0
        with torch.no_grad():
            for images, masks in val_loader:
                images, masks = images.to(device), masks.to(device)
                logits = model(images)
                loss = criterion(logits, masks)
                val_loss += loss.item()
                iou, dice = compute_metrics(logits, masks)
                val_iou += iou
                val_dice += dice

        print(f"Epoch [{epoch+1}/{epochs}] | "
              f"Train Loss: {train_loss/len(train_loader):.4f} | Val Loss: {val_loss/len(val_loader):.4f} | "
              f"Val Dice: {val_dice/len(val_loader):.4f}")


    save_path = '/content/unet_lgg_weights.pth'
    torch.save(model.state_dict(), save_path)
    print(f"\nTraining Complete! Model saved to {save_path}")


    print("\nVisualizing Validation Predictions...")
    visualize_predictions(model, val_loader, device)

if __name__ == "__main__":
    training()

